name: Pre-release ci tasks

on:
  workflow_call:
    inputs:
      run-ci:
        description: 'run the ci workflow'
        required: true
        type: boolean

      codeql:
        description: 'run the codeql workflow'
        required: true
        type: boolean

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    if: ${{ inputs.run-ci }}

  ci-skipped:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ always() && needs.ci.result == 'skipped' }}
    steps:
      - run: echo CI Skipped

  codeql:
    uses: ./.github/workflows/codeql.yml
    if: ${{ inputs.codeql }}

  codeql-skipped:
    runs-on: ubuntu-latest
    needs: codeql
    if: ${{ always() && needs.codeql.result == 'skipped' }}
    steps:
      - run: echo Codeql Skipped