name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Is release? (Will create tag and update version)
        required: true
        default: false
        type: boolean
      release-version:
        description: Released version (x.y.z)
        required: true
        type: string
      next-version:
        description: Next version (x.y.z)
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  pre-release:
    name: Update version, tag repo, and return sha
    needs: [ ci, codeql ]
    uses: ./.github/workflows/pre-release.yml
    with:
      release: ${{ inputs.release }}
      version: ${{ inputs.release-version }}

  release:
    name: Release java artifacts
    permissions:
      contents: read
      packages: write
    needs: pre-release
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-release.outputs.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}

  post-release:
    name: Update version
    needs: release
    uses: ./.github/workflows/post-release.yml
    with:
      release: ${{ inputs.release }}
      version: ${{ inputs.next-version }}